[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
version = "0.0.1"
description = "A simple project"
authors = [
    { name = "Slav. B.", email = "slav_b@ukr.net" }
]
requires-python = ">=3.10"
